### PR TITLE
Implement images className and srcSet 

### PR DESCRIPTION
**Pull request by damien916**
Hello :)
Thanks for your work.
I just add props:

- imageClassName
- enlargedImageClassName
- enlargedImageContainerClassName
- srcSet (Image object)

### CODE REVIEW

**Comment by ethanselzer** [comment]
@damien916 - Thank you for your very nice contribution! I will update the NPM package now and comment here when that is complete.

**Comment by ethanselzer** [comment]
The [NPM package](https://www.npmjs.com/package/react-image-magnify) has been updated and a [release has been tagged](https://github.com/ethanselzer/react-image-magnify/releases) on GitHub. Thanks again! I hope react-image-magnify is useful to you!

**Comment by damien916** [comment]
@ethanselzer thank you, react-image-magnify is very useful for my project :)

**Comment by ethanselzer** [comment]
@damien916 - I really appreciate your contributions to react-image-magnify. I'm so glad it is useful to you. Please consider [starring the project](https://github.com/ethanselzer/react-image-magnify/stargazers) :).

**Pull request merged**
