### PR TITLE
+ onLoad prop for images

### PR DESCRIPTION
**Pull request by sk1e**
Hi, adding optional onLoad prop for small and large images.

### CODE REVIEW

**Comment by ethanselzer** [comment]
Hi @sk1e - This looks great! I think your PR introduces useful features. I'm wondering how comfortable you are with documenting the new features on [readme.md](https://github.com/ethanselzer/react-image-magnify#small-image). Please let me know. I opened a PR to your fork with a suggested change. Please have a look.

**Comment by sk1e** [comment]
@ethanselzer I'm glad you find it useful. I'll resolve your suggestions shortly.

**Comment by sk1e** [comment]
@ethanselzer Not sure how to specify a type for the function: just `Function` or maybe it would be better to show its range and domain in typescript notation — `() => void` or both — `Function (() => void)`. I would prefer the last one since I think that signatures are important and it keeps your documentation style.

**Comment by ethanselzer** [comment]
@sk1e - Very nice! I want to thank you again for your contribution. If you find react-image-magnify useful, please consider starring it on GitHub. Starring helps to grow the project, which benefits everyone.

**Comment by ethanselzer** [comment]
Please see [release notes](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.1.0)

**Comment by sk1e** [comment]
@ethanselzer it's been nice working with you. Cheers :)

**Comment by ethanselzer** [comment]
@sk1e - I has been great working with you also. Thanks again!

**Pull request merged**
