### PR TITLE
Add onError prop for images

### PR DESCRIPTION
**Pull request by spiderbites**
Hello, this PR adds an optional onError prop for small and large images. I followed exactly the approach for adding the onLoad prop which came in a recent PR.

Cheers!

### CODE REVIEW

**Comment by ethanselzer** [comment]
Hi @spiderbites - Thanks for suggesting we support the image error event! I think it is a useful feature. I appreciate you following the pre-existing load event pattern but I would like to propose we change that pattern a little. I opened a [PR to your branch](https://github.com/spiderbites/react-image-magnify/pull/1) with suggested changes. Please have a look and and if you agree with the changes, merge them into your branch, which will update your PR.

**Comment by spiderbites** [comment]
Works for me!

**Comment by ethanselzer** [comment]
@spiderbites - Version 2.3.0 is now available on NPM. Thanks again for contributing a great feature!
[NPM Package](https://www.npmjs.com/package/react-image-magnify)
[Release Notes](https://github.com/ethanselzer/react-image-magnify/releases/edit/v2.3.0)

**Comment by spiderbites** [comment]
Thanks for getting this in so quickly and for all your work on this component!

**Pull request merged**
